### ISSUE TITLE
Inconsistent Type Error (User/Bot)

### ISSUE THREAD

**Issue by lkngtn** [sourcecred/sourcecred#1362] opened 2019-09-09 18:47 UTC
I got the following error when trying to run sourcecred on the @aragon organization. 

``` $ node bin/sourcecred.js load @aragon
  GO   load-@aragon
  GO   github/aragon/aragon
Error: Inconsistent type for ID "MDM6Qm90NDY0NDczMjE=": expected "Bot", got "User"
    at Mirror._nontransactionallyRegisterObject (webpack:///./src/graphql/mirror.js?:190:76)
    at Mirror._nontransactionallyRegisterNodeFieldResult (webpack:///./src/graphql/mirror.js?:205:214)
    at Mirror._nontransactionallyUpdateOwnData (webpack:///./src/graphql/mirror.js?:432:560)
    at Mirror._nontransactionallyUpdateData (webpack:///./src/graphql/mirror.js?:247:235)
    at _inTransaction (webpack:///./src/graphql/mirror.js?:252:638)
    at _inTransaction (webpack:///./src/graphql/mirror.js?:568:142)
    at Mirror._updateStep (webpack:///./src/graphql/mirror.js?:252:555)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by decentralion** [comment] 2019-09-10 02:41
Looks like another instance of https://github.com/sourcecred/sourcecred/issues/998.

The simplest thing to do for now would be to update the blacklist, so as to blacklist that id. This usually unblocks loading affected repositories while we punt on a full fix.

Here's an example of such a blacklist update: https://github.com/sourcecred/sourcecred/pull/1335

**Comment by wchargin** [comment] 2019-09-10 02:41
Indeed. This is due to a bug in the GitHub API: there are cases where
GitHub claims that it is returning a `User` but it actually provides
data about a `Bot`:
<https://github.com/sourcecred/sourcecred/issues/996#issuecomment-435495461>

A proper solution to this is on our radar; in the meantime, you can
blacklist that particular bot so that it doesn’t cause trouble. To do
so, add the bad node ID (`MDM6Qm90NDY0NDczMjE=`) to `BLACKLISTED_IDS`,
defined in `src/plugins/github/blacklistObjectIds.js`. You’ll then need
to clear your download cache (`/tmp/sourcecred/cache/`) and restart the
load job.

I also recommend updating to latest SourceCred; as of #1337, we now
print out a warning when we suspect that this is likely to happen, with
additional information that may be helpful. (Sometimes, in addition to
blacklisting one node, you need to blacklist related nodes in the graph,
and the warnings in #1337 can include that information.)

**Comment by lkngtn** [comment] 2019-09-10 15:17
> A proper solution to this is on our radar; in the meantime, you can
> blacklist that particular bot so that it doesn’t cause trouble. To do
> so, add the bad node ID (`MDM6Qm90NDY0NDczMjE=`) to `BLACKLISTED_IDS`,
> defined in `src/plugins/github/blacklistObjectIds.js`. You’ll then need
> to clear your download cache (`/tmp/sourcecred/cache/`) and restart the
> load job.

I tried this and got the same result...

I don't have a `/tmp/sourcecred/cache/` (possibly because im running on OS X), but I removed the cache from the `SOURCECRED_DIRECTORY`. 

> I also recommend updating to latest SourceCred; as of #1337, we now
> print out a warning when we suspect that this is likely to happen, with
> additional information that may be helpful. (Sometimes, in addition to
> blacklisting one node, you need to blacklist related nodes in the graph,
> and the warnings in #1337 can include that information.)

I'm currently running from source with the latest version in master. And don't see the warnings, just the error with `MDM6Qm90NDY0NDczMjE=`. Is there a different branch I should be using?

**Comment by wchargin** [comment] 2019-09-10 15:58
> but I removed the cache from the `SOURCECRED_DIRECTORY`.

Right; yes.

> I tried this and got the same result...

Did you perhaps forget to run `yarn backend` to rebuild the application
binaries before restarting the job? Loading `aragon/aragon` on current
master works for me after running `yarn backend`, now that #1363 has
merged; prior to that, I could reproduce the failure as you describe.

Can you try checking out latest `origin/master`, running `yarn backend`,
and re-running the job? Let us know if that works for you.

> I'm currently running from source with the latest version in master.
> And don't see the warnings, just the error with
> `MDM6Qm90NDY0NDczMjE=`. Is there a different branch I should be using?

You’re on the correct branch. It looks like we don’t see the warnings in
this case, because GitHub gives us the correct typename _first_, so we
never insert the bad typename and are not at risk of corrupting the
database. (This also means that the warnings aren’t _needed_.)

Details, in case you’re interested:

<details>

Here’s (approximately) the GraphQL query that we send…

```graphql
{
  repository(owner: "aragon", name: "aragon") {
    pullRequest(number: 766) {
      author {
        __typename
        ... on Bot {
          login
          id
        }
      }
      mergeCommit {
        author {
          user {
            __typename
            login
            id
          }
        }
      }
    }
  }
}
```

…and the response that we get:

```json
{
  "data": {
    "repository": {
      "pullRequest": {
        "author": {
          "__typename": "Bot",
          "login": "allcontributors",
          "id": "MDM6Qm90NDY0NDczMjE="
        },
        "mergeCommit": {
          "author": {
            "user": {
              "__typename": "User",
              "login": "allcontributors[bot]",
              "id": "MDM6Qm90NDY0NDczMjE="
            }
          }
        }
      }
    }
  }
}
```

Note that the `id`s are the same for the `pullRequest.author` and the
`mergeCommit.author.user`, but that the `__typename`s and `login`s are
different. The typename that we process first (on `pullRequest.author`,
because the PR is a parent object of the merge commit) is correct, so we
insert it into the database without warning. When we encounter the bad
typename, we fail before inserting it into the database, and so the
database is never corrupted.

</details>

**Comment by lkngtn** [comment] 2019-09-10 16:53
> Did you perhaps forget to run yarn backend to rebuild the application
binaries before restarting the job? Loading aragon/aragon on current
master works for me after running yarn backend, now that #1363 has
merged; prior to that, I could reproduce the failure as you describe. 

This did the trick! Thanks!

**Comment by wchargin** [comment] 2019-09-11 07:32
Great; glad to hear it! I’ll close this out; feel free to let us know if
you hit any further issues.

**Closed by wchargin** 2019-09-11 07:32 UTC
