### ISSUE TITLE
Relative links for legacy/timeline switcher

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1318] opened 2019-08-22 13:13 UTC
We're hosting our sourcecred instance at `sfosc.org/sourcecred`.
However links to switch between legacy / timeline cred are absolute.

So on https://sfosc.org/sourcecred/timeline/@sfosc/
the `(legacy)` link points to https://sfosc.org/prototype/@sfosc/

And vice versa https://sfosc.org/sourcecred/prototype/@sfosc/
the `timeline mode` link points to https://sfosc.org/timeline/@sfosc/

Having relative links, would fix this issue.

**Comment by wchargin** [comment] 2019-08-22 15:31
It’s a bit more complicated than just using relative links, but this
should have been fixed by #1305. Can you update to latest master and try
re-building?

**Comment by wchargin** [comment] 2019-08-22 15:34
For an explanation of why we don’t just use relative links everywhere,
you may find it helpful to read the doc comment at:
https://github.com/sourcecred/sourcecred/blob/acdcbc29ede149116cf61a04c3ecb2a7f4196ab1/src/webutil/createRelativeHistory.js#L4-L39

**Comment by wchargin** [comment] 2019-08-23 15:46
Assuming that this is a duplicate of #1304, which has been fixed. If
not, please feel free to specify what’s different and reopen.

**Comment by wchargin** [comment] 2019-08-23 15:46
Duplicate of #1304

**Closed by wchargin** 2019-08-23 15:46 UTC
